### PR TITLE
Prevent logs from being index by search engines.

### PR DESCRIPTION
**Pull request by ADmad**
Some users have raised concerns about irclogs being accessible to search engines.

### CODE REVIEW

**Comment by ADmad** [comment]
These changes don't show up on irc.cakephp.org. I have no idea how the deployment is done.

**Comment by josegonzalez** [comment]
I think it's a git pull on the servers (from the last time I tried to deploy). I can do that now.

Note: logging is hella broken if you're on ipv6, so maybe just have them upgrade :P

**Comment by josegonzalez** [comment]
Also, the logs were meant to be searchable, is there a reason why we should avoid logging? Just curious, it's not like we tell people they are being logged.

**Comment by ADmad** [comment]
@phpnut said few people had expressed concerns about irc logs showing up in search engine results. Plus no one really searches the logs for answers. So if preventing them from being indexed keeps people happy so be it.

**Comment by josegonzalez** [comment]
Fair enough.

**Comment by josegonzalez** [comment]
Deployed!

**Comment by ADmad** [comment]
Thx

**Pull request merged**
